image:
  repository: acrboutiquedevweu.azurecr.io/backend
  digest: "sha256:f606dc82e109b086f8eb10f4cd8ebce34e7dec7ae6e253fc19ed132400b86925"

ingress:
  host: api-dev.boutique.biroltilki.art
  tls:
    secretName: backend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
