image:
  repository: acrboutiquedevweu.azurecr.io/backend
  digest: "sha256:b4246f4eb8782febca57dbf00319a10951e0c48e492c18eda9805d95afe42ee3"

ingress:
  host: api-dev.boutique.biroltilki.art
  tls:
    secretName: backend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
