image:
  repository: acrboutiquedevweu.azurecr.io/frontend
  digest: "sha256:2763a02553a82a52d1dc38a529f84c5dfebc287aa50f098599754a489150b6dd"

ingress:
  host: dev.boutique.biroltilki.art
  tls:
    secretName: frontend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
