image:
  repository: acrboutiquedevweu.azurecr.io/frontend
  digest: "sha256:ca247a69145a42d7c588bc87ff46775499643210f136a6f32b25f212df52000b"

ingress:
  host: dev.boutique.biroltilki.art
  tls:
    secretName: frontend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
