image:
  repository: acrboutiquedevweu.azurecr.io/redis-cart
  digest: "sha256:001a7418ccb17cedb0a5a24983709b4494eaf945973cefb9baba9bad0cba2c1e"

service:
  port: 6379
  targetPort: 6379

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
