image:
  repository: acrboutiquedevweu.azurecr.io/frontend
  digest: "sha256:fe19148d22aa8f86aed1c222be9cd2e06492cc4f365520dc874e1a73d3591efa"

ingress:
  host: dev.boutique.biroltilki.art
  tls:
    secretName: frontend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
