image:
  repository: acrboutiquedevweu.azurecr.io/backend
  digest: "sha256:e1ae694c2891b14f5599154037b5248a30fc448c91abaceadc0b98e1ecc7b9ce"

ingress:
  host: api-dev.boutique.biroltilki.art
  tls:
    secretName: backend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
