image:
  repository: acrboutiquedevweu.azurecr.io/productcatalogservice
  digest: "sha256:e779d2668d8aad1ed1d5572adb57d80c7c06c9c722f74b9e4f347aebadc5e275"

service:
  port: 3550
  targetPort: 3550

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
